name: 'Monthly Publish'

on:
  schedule:
    - cron:  '0 4 1 * *'

jobs:
  monthly-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Monthly Publish
      env:
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: wget -q https://git.io/Je8ON -O monthly-publish.sh  && bash monthly-publish.sh
